project_id = "vzpissitddpunkpythsb"

[functions.run-migrations]
verify_jwt = false

[functions.run-seeds]
verify_jwt = false

[functions.seed-data-2025]
verify_jwt = false

[functions.optimizer-seed-tesu]
verify_jwt = false

[functions.optimizer-seed-cosc]
verify_jwt = false

[functions.optimizer-seed-excelsior]
verify_jwt = false

