import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Loader2 } from 'lucide-react';

interface ShareRow {
  title: string | null;
  metrics_snapshot: any;
  created_at: string;
}

export default function ShareTrust() {
  const { token } = useParams();
  const [share, setShare] = useState<ShareRow | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const run = async () => {
      if (!token) return;
      try {
        const { data, error } = await supabase
          .from('trust_badge_shares')
          .select('title, metrics_snapshot, created_at, visibility, expires_at')
          .eq('share_token', token)
          .eq('visibility', 'public')
          .maybeSingle();
        if (error) throw error;
        if (!data) {
          setError('This trust badge is not available.');
        } else if (data.expires_at && new Date(data.expires_at) < new Date()) {
          setError('This trust badge has expired.');
        } else {
          setShare({ title: data.title, metrics_snapshot: data.metrics_snapshot, created_at: data.created_at });
        }
      } catch (e: any) {
        setError(e.message ?? 'Unable to load trust badge');
      } finally {
        setLoading(false);
      }
    };
    run();
  }, [token]);

  const title = share?.title || 'Maya Trust Badge';
  const m = share?.metrics_snapshot || {};

  return (
    <div className="min-h-screen bg-background">
      <Helmet>
        <title>{title} | Life Path AI</title>
        <meta name="description" content="Public Maya Trust Badge showcasing trust, satisfaction, accuracy, and feedback metrics." />
        <link rel="canonical" href={(typeof window !== 'undefined' ? window.location.href : '')} />
      </Helmet>
      <main className="container mx-auto px-4 py-10">
        <header className="mb-6">
          <h1 className="text-2xl font-semibold">{title}</h1>
          <p className="text-sm text-muted-foreground">Generated by Life Path AI</p>
        </header>

        {loading ? (
          <div className="h-40 flex items-center justify-center"><Loader2 className="h-6 w-6 animate-spin" /></div>
        ) : error ? (
          <Card>
            <CardHeader>
              <CardTitle>Unavailable</CardTitle>
              <CardDescription>{error}</CardDescription>
            </CardHeader>
          </Card>
        ) : (
          <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <Card>
              <CardHeader>
                <CardTitle className="text-sm">Trust Score</CardTitle>
                <CardDescription>Overall confidence</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-baseline gap-2">
                  <span className="text-3xl font-bold">{m?.trust_score?.toFixed?.(1) ?? '—'}</span>
                  <Badge>0-100</Badge>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-sm">Satisfaction</CardTitle>
                <CardDescription>User-rated experience</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-baseline gap-2">
                  <span className="text-3xl font-bold">{m?.satisfaction_score?.toFixed?.(1) ?? '—'}</span>
                  <Badge>0-100</Badge>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-sm">Accuracy</CardTitle>
                <CardDescription>Positive outcomes</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-baseline gap-2">
                  <span className="text-3xl font-bold">{m?.recommendation_accuracy?.toFixed?.(1) ?? '—'}%</span>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-sm">Feedback Volume</CardTitle>
                <CardDescription>Last 90 days</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-baseline gap-2">
                  <span className="text-3xl font-bold">{m?.feedback_volume ?? 0}</span>
                </div>
              </CardContent>
            </Card>
          </section>
        )}
      </main>
    </div>
  );
}
