import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { 
  Target, 
  Workflow, 
  CheckCircle, 
  Clock, 
  ArrowRight,
  Zap,
  Settings,
  Play,
  Pause,
  RotateCcw,
  Brain,
  TrendingUp
} from 'lucide-react';
import { useEnhancedGoals } from '@/hooks/useEnhancedGoals';
import { useAIPlanningEngine } from '@/hooks/useAIPlanningEngine';
import { useAutonomousWorkflows } from '@/hooks/useAutonomousWorkflows';

interface GoalOrchestratorProps {
  userId: string;
}

interface WorkflowStep {
  id: string;
  title: string;
  description: string;
  type: 'course' | 'skill' | 'project' | 'certification';
  status: 'pending' | 'active' | 'completed' | 'paused';
  estimatedTime: string;
  dependencies: string[];
  autoGenerated: boolean;
  mayaOptimized: boolean;
}

interface GoalWorkflow {
  id: string;
  goalId: string;
  goalTitle: string;
  status: 'draft' | 'active' | 'paused' | 'completed';
  progress: number;
  steps: WorkflowStep[];
  autoAdjusting: boolean;
  mayaConfidence: number;
  nextRecommendation?: string;
}

export function GoalOrchestrator({ userId }: GoalOrchestratorProps) {
  const [activeTab, setActiveTab] = useState('overview');
  const [goalWorkflows, setGoalWorkflows] = useState<GoalWorkflow[]>([]);
  const [autoOptimization, setAutoOptimization] = useState(true);
  
  const { userGoals, createGoal, isLoadingGoals } = useEnhancedGoals(userId);
  const { loading: planningLoading } = useAIPlanningEngine();
  const { workflows, createWorkflow } = useAutonomousWorkflows();

  // Initialize goal workflows from user goals
  useEffect(() => {
    if (userGoals && userGoals.length > 0) {
      const mockWorkflows: GoalWorkflow[] = userGoals.slice(0, 3).map((goal, index) => ({
        id: `workflow-${goal.id}`,
        goalId: goal.id,
        goalTitle: goal.title,
        status: index === 0 ? 'active' : index === 1 ? 'draft' : 'paused',
        progress: index === 0 ? 65 : index === 1 ? 0 : 25,
        autoAdjusting: autoOptimization,
        mayaConfidence: 0.85 + (index * 0.05),
        steps: generateMockSteps(goal.title, index),
        nextRecommendation: index === 0 ? 'Complete React Hooks course by Friday' : undefined
      }));
      
      setGoalWorkflows(mockWorkflows);
    }
  }, [userGoals, autoOptimization]);

  const generateMockSteps = (goalTitle: string, index: number): WorkflowStep[] => {
    const baseSteps = [
      {
        id: `step-1-${index}`,
        title: 'Foundation Learning',
        description: 'Complete prerequisite knowledge areas',
        type: 'course' as const,
        status: index === 0 ? 'completed' : 'pending' as const,
        estimatedTime: '2 weeks',
        dependencies: [],
        autoGenerated: true,
        mayaOptimized: true
      },
      {
        id: `step-2-${index}`,
        title: 'Practical Application',
        description: 'Build hands-on project to apply skills',
        type: 'project' as const,
        status: index === 0 ? 'active' : 'pending' as const,
        estimatedTime: '3 weeks',
        dependencies: [`step-1-${index}`],
        autoGenerated: true,
        mayaOptimized: true
      },
      {
        id: `step-3-${index}`,
        title: 'Skill Certification',
        description: 'Obtain relevant industry certification',
        type: 'certification' as const,
        status: 'pending' as const,
        estimatedTime: '1 week',
        dependencies: [`step-2-${index}`],
        autoGenerated: true,
        mayaOptimized: false
      },
      {
        id: `step-4-${index}`,
        title: 'Portfolio Integration',
        description: 'Add completed work to professional portfolio',
        type: 'skill' as const,
        status: 'pending' as const,
        estimatedTime: '1 week',
        dependencies: [`step-3-${index}`],
        autoGenerated: false,
        mayaOptimized: true
      }
    ];

    return baseSteps;
  };

  const handleStartWorkflow = async (workflowId: string) => {
    setGoalWorkflows(prev => prev.map(workflow => 
      workflow.id === workflowId 
        ? { ...workflow, status: 'active' }
        : workflow
    ));
  };

  const handlePauseWorkflow = (workflowId: string) => {
    setGoalWorkflows(prev => prev.map(workflow => 
      workflow.id === workflowId 
        ? { ...workflow, status: 'paused' }
        : workflow
    ));
  };

  const handleOptimizeWorkflow = async (workflowId: string) => {
    // Simulate Maya optimization
    setGoalWorkflows(prev => prev.map(workflow => 
      workflow.id === workflowId 
        ? { 
            ...workflow, 
            mayaConfidence: Math.min(0.95, workflow.mayaConfidence + 0.1),
            steps: workflow.steps.map(step => ({
              ...step,
              mayaOptimized: true,
              estimatedTime: step.estimatedTime.includes('week') 
                ? step.estimatedTime.replace(/\d+/, (match) => String(Math.max(1, parseInt(match) - 1)))
                : step.estimatedTime
            }))
          }
        : workflow
    ));
  };

  const getStepIcon = (type: WorkflowStep['type']) => {
    switch (type) {
      case 'course': return '📚';
      case 'skill': return '🛠️';
      case 'project': return '🚀';
      case 'certification': return '🏆';
      default: return '📋';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed': return 'text-green-500';
      case 'active': return 'text-blue-500';
      case 'paused': return 'text-yellow-500';
      case 'pending': return 'text-muted-foreground';
      default: return 'text-muted-foreground';
    }
  };

  if (isLoadingGoals) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Target className="w-5 h-5 text-blue-500" />
            Goal Orchestrator
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center h-32">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Orchestrator Overview */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-3">
            <div className="p-2 bg-gradient-to-br from-green-500/20 to-blue-500/20 rounded-lg">
              <Target className="w-6 h-6 text-green-500" />
            </div>
            <div>
              <h2 className="text-xl font-bold">Goal Orchestrator</h2>
              <p className="text-muted-foreground">Smart goal → workflow automation</p>
            </div>
            <div className="ml-auto flex items-center gap-2">
              <Badge variant={autoOptimization ? "default" : "secondary"}>
                Auto-Optimization: {autoOptimization ? 'ON' : 'OFF'}
              </Badge>
              <Button 
                variant="outline" 
                size="sm"
                onClick={() => setAutoOptimization(!autoOptimization)}
              >
                <Settings className="w-4 h-4" />
              </Button>
            </div>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="text-center space-y-2">
              <div className="text-2xl font-bold">{goalWorkflows.length}</div>
              <div className="text-sm text-muted-foreground">Active Workflows</div>
            </div>
            <div className="text-center space-y-2">
              <div className="text-2xl font-bold">
                {goalWorkflows.filter(w => w.status === 'active').length}
              </div>
              <div className="text-sm text-muted-foreground">Running</div>
            </div>
            <div className="text-center space-y-2">
              <div className="text-2xl font-bold">
                {Math.round(goalWorkflows.reduce((acc, w) => acc + w.progress, 0) / goalWorkflows.length) || 0}%
              </div>
              <div className="text-sm text-muted-foreground">Avg Progress</div>
            </div>
            <div className="text-center space-y-2">
              <div className="text-2xl font-bold">
                {Math.round(goalWorkflows.reduce((acc, w) => acc + w.mayaConfidence, 0) / goalWorkflows.length * 100) || 0}%
              </div>
              <div className="text-sm text-muted-foreground">Maya Confidence</div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Workflow Management Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="overview">Workflow Overview</TabsTrigger>
          <TabsTrigger value="automation">Automation Engine</TabsTrigger>
          <TabsTrigger value="optimization">AI Optimization</TabsTrigger>
        </TabsList>

        <TabsContent value="overview" className="space-y-4">
          {goalWorkflows.map((workflow) => (
            <Card key={workflow.id}>
              <CardHeader>
                <CardTitle className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="flex items-center gap-2">
                      <Workflow className={`w-5 h-5 ${getStatusColor(workflow.status)}`} />
                      <span>{workflow.goalTitle}</span>
                    </div>
                    <Badge variant="outline" className="capitalize">
                      {workflow.status}
                    </Badge>
                  </div>
                  <div className="flex items-center gap-2">
                    {workflow.status === 'active' ? (
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => handlePauseWorkflow(workflow.id)}
                      >
                        <Pause className="w-4 h-4" />
                      </Button>
                    ) : (
                      <Button 
                        variant="outline" 
                        size="sm"
                        onClick={() => handleStartWorkflow(workflow.id)}
                      >
                        <Play className="w-4 h-4" />
                      </Button>
                    )}
                    <Button 
                      variant="outline" 
                      size="sm"
                      onClick={() => handleOptimizeWorkflow(workflow.id)}
                    >
                      <Brain className="w-4 h-4" />
                    </Button>
                  </div>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {/* Progress Overview */}
                  <div className="flex items-center justify-between mb-4">
                    <span className="text-sm text-muted-foreground">
                      Overall Progress: {workflow.progress}%
                    </span>
                    <span className="text-sm text-muted-foreground">
                      Maya Confidence: {Math.round(workflow.mayaConfidence * 100)}%
                    </span>
                  </div>
                  <Progress value={workflow.progress} className="w-full" />

                  {/* Next Recommendation */}
                  {workflow.nextRecommendation && (
                    <Alert>
                      <Brain className="h-4 w-4" />
                      <AlertDescription>
                        <strong>Maya Recommendation:</strong> {workflow.nextRecommendation}
                      </AlertDescription>
                    </Alert>
                  )}

                  {/* Workflow Steps */}
                  <div className="space-y-3">
                    {workflow.steps.map((step, index) => (
                      <div key={step.id} className="flex items-center gap-3 p-3 border rounded-lg">
                        <div className="text-2xl">{getStepIcon(step.type)}</div>
                        <div className="flex-1">
                          <div className="flex items-center gap-2">
                            <span className="font-medium">{step.title}</span>
                            {step.mayaOptimized && (
                              <Badge variant="secondary" className="text-xs">
                                <Brain className="w-3 h-3 mr-1" />
                                Maya
                              </Badge>
                            )}
                            {step.autoGenerated && (
                              <Badge variant="outline" className="text-xs">
                                Auto
                              </Badge>
                            )}
                          </div>
                          <div className="text-sm text-muted-foreground">{step.description}</div>
                          <div className="flex items-center gap-4 mt-1">
                            <span className="text-xs text-muted-foreground flex items-center gap-1">
                              <Clock className="w-3 h-3" />
                              {step.estimatedTime}
                            </span>
                            <Badge 
                              variant="outline" 
                              className={`text-xs ${getStatusColor(step.status)}`}
                            >
                              {step.status}
                            </Badge>
                          </div>
                        </div>
                        {index < workflow.steps.length - 1 && (
                          <ArrowRight className="w-4 h-4 text-muted-foreground" />
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </TabsContent>

        <TabsContent value="automation" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Zap className="w-5 h-5" />
                Automation Engine
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-4 border rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                      <CheckCircle className="w-5 h-5 text-green-500" />
                      <span className="font-medium">Auto-Generation Active</span>
                    </div>
                    <div className="text-sm text-muted-foreground">
                      Workflows are automatically generated from goals using Maya AI
                    </div>
                  </div>
                  
                  <div className="p-4 border rounded-lg">
                    <div className="flex items-center gap-2 mb-2">
                      <TrendingUp className="w-5 h-5 text-blue-500" />
                      <span className="font-medium">Smart Adaptation</span>
                    </div>
                    <div className="text-sm text-muted-foreground">
                      Workflows adapt based on your progress and performance
                    </div>
                  </div>
                </div>

                <div className="p-4 bg-muted/50 rounded-lg">
                  <h4 className="font-medium mb-2">Automation Rules</h4>
                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span>Auto-generate learning paths from goals</span>
                      <Badge variant="secondary">Active</Badge>
                    </div>
                    <div className="flex justify-between">
                      <span>Adjust difficulty based on performance</span>
                      <Badge variant="secondary">Active</Badge>
                    </div>
                    <div className="flex justify-between">
                      <span>Recommend optimal study times</span>
                      <Badge variant="secondary">Active</Badge>
                    </div>
                    <div className="flex justify-between">
                      <span>Auto-pause on low engagement</span>
                      <Badge variant="outline">Disabled</Badge>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="optimization" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Brain className="w-5 h-5" />
                Maya AI Optimization
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="p-4 border rounded-lg">
                  <div className="font-medium mb-2">Optimization Insights</div>
                  <div className="space-y-3">
                    <div className="flex items-center justify-between p-3 bg-blue-50 dark:bg-blue-950/20 rounded-lg">
                      <div>
                        <div className="font-medium text-sm">Learning Path Efficiency</div>
                        <div className="text-xs text-muted-foreground">Maya has optimized your paths for 23% faster completion</div>
                      </div>
                      <Badge variant="secondary">+23%</Badge>
                    </div>
                    
                    <div className="flex items-center justify-between p-3 bg-green-50 dark:bg-green-950/20 rounded-lg">
                      <div>
                        <div className="font-medium text-sm">Success Rate Prediction</div>
                        <div className="text-xs text-muted-foreground">Current workflow has 92% predicted success rate</div>
                      </div>
                      <Badge variant="secondary">92%</Badge>
                    </div>
                    
                    <div className="flex items-center justify-between p-3 bg-yellow-50 dark:bg-yellow-950/20 rounded-lg">
                      <div>
                        <div className="font-medium text-sm">Skill Gap Analysis</div>
                        <div className="text-xs text-muted-foreground">3 prerequisite skills identified for acceleration</div>
                      </div>
                      <Button variant="outline" size="sm">
                        View Details
                      </Button>
                    </div>
                  </div>
                </div>

                <div className="p-4 border rounded-lg">
                  <div className="font-medium mb-2">Optimization Controls</div>
                  <div className="grid grid-cols-2 gap-4">
                    <Button variant="outline" className="justify-start">
                      <RotateCcw className="w-4 h-4 mr-2" />
                      Re-optimize All Workflows
                    </Button>
                    <Button variant="outline" className="justify-start">
                      <Settings className="w-4 h-4 mr-2" />
                      Optimization Settings
                    </Button>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}