-- Add demo career tracks for Mateo using profile id
INSERT INTO career_tracks (
  user_id,
  title,
  track_name,
  description,
  slug,
  growth_potential,
  reasoning,
  time_to_proficiency,
  switch_readiness_score,
  roi_score,
  risk_score,
  order_index
) VALUES 
(
  '80c8790f-0579-4257-98a0-f3d72d950469', -- Mateo's profile id
  'Full Stack Web Developer',
  'Full Stack Web Developer',
  'Master modern web development with React, Node.js, and databases. Build complete web applications from frontend to backend.',
  'fullstack-web-developer',
  'Strong growth with 15-20% job growth projected. Salaries range from $65,000-$120,000+ with remote opportunities.',
  'Perfect for someone starting in tech. High demand, transferable skills, and great entry point into software development.',
  '8-12 months',
  85.5,
  78.2,
  25.3,
  0
),
(
  '80c8790f-0579-4257-98a0-f3d72d950469',
  'Data Analyst',
  'Data Analyst',
  'Analyze data to drive business decisions using SQL, Python, and visualization tools like Tableau and Power BI.',
  'data-analyst',
  'Excellent growth potential with increasing demand for data-driven insights. Salaries $55,000-$95,000+.',
  'Great analytical career path with strong job security. Skills transfer across industries.',
  '6-9 months',
  75.8,
  72.4,
  22.1,
  1
),
(
  '80c8790f-0579-4257-98a0-f3d72d950469',
  'Product Manager', 
  'Product Manager',
  'Bridge technical and business teams to build products users love. Focus on strategy, user research, and roadmap planning.',
  'product-manager',
  'High growth field with excellent compensation $90,000-$150,000+. Tech companies always need great PMs.',
  'Leverages communication skills and business sense. No coding required but technical understanding helpful.',
  '10-14 months',
  68.9,
  82.6,
  28.7,
  2
),
(
  '80c8790f-0579-4257-98a0-f3d72d950469',
  'UX/UI Designer',
  'UX/UI Designer', 
  'Design user-friendly interfaces and experiences. Combine creativity with user psychology to solve design problems.',
  'ux-ui-designer',
  'Strong demand for digital experiences. Salaries $60,000-$110,000+ with freelance opportunities.',
  'Perfect blend of creativity and technology. Growing field with remote work options.',
  '6-10 months',
  71.2,
  69.8,
  24.5,
  3
),
(
  '80c8790f-0579-4257-98a0-f3d72d950469',
  'Cloud Engineer',
  'Cloud Engineer',
  'Build and manage cloud infrastructure on AWS, Azure, or Google Cloud. Focus on scalability and reliability.',
  'cloud-engineer',
  'Explosive growth in cloud adoption. High salaries $80,000-$130,000+ with excellent job security.',
  'Future-proof career path. Essential skills as companies move to cloud-first strategies.',
  '8-12 months',
  66.3,
  85.1,
  19.8,
  4
);