-- Insert Data Analyst related skills with slugs
INSERT INTO public.skills (name, slug, category, description) VALUES
  ('Statistics', 'statistics', 'Math & Analytics', 'Understanding distributions, averages, standard deviation, and hypothesis testing.'),
  ('Probability', 'probability', 'Math & Analytics', 'Foundational skill for uncertainty, forecasting, and experiments.'),
  ('Hypothesis Testing', 'hypothesis-testing', 'Math & Analytics', 'Used in A/B testing and statistical decision making.'),
  ('Excel', 'excel', 'Tools', 'Widely used spreadsheet software for data analysis and reporting.'),
  ('Pivot Tables', 'pivot-tables', 'Tools', 'Excel feature for summarizing and analyzing data.'),
  ('VLOOKUP', 'vlookup', 'Tools', 'Function used in Excel to look up values across tables.'),
  ('SQL', 'sql', 'Programming', 'Structured Query Language used to extract and manipulate data.'),
  ('Database Querying', 'database-querying', 'Programming', 'Accessing and filtering large datasets using SQL.'),
  ('Joins', 'joins', 'Programming', 'Combining data from multiple tables using SQL.'),
  ('Aggregations', 'aggregations', 'Programming', 'Summarizing and grouping data in SQL.'),
  ('Python', 'python', 'Programming', 'General purpose language used heavily in data analysis.'),
  ('Pandas', 'pandas', 'Programming', 'Python library for tabular data manipulation.'),
  ('NumPy', 'numpy', 'Programming', 'Python library for numerical computing.'),
  ('Matplotlib', 'matplotlib', 'Programming', 'Python library for plotting and data visualization.'),
  ('Tableau', 'tableau', 'Visualization', 'Tool for building interactive data dashboards.'),
  ('Data Cleaning', 'data-cleaning', 'Data Processing', 'Detecting and fixing issues in raw data sets.'),
  ('Business Analytics', 'business-analytics', 'Strategy', 'Using data to drive business decision-making.'),
  ('Google Analytics', 'google-analytics', 'Web Analytics', 'Used to track and report website traffic.'),
  ('Portfolio Development', 'portfolio-development', 'Career Prep', 'Documenting and presenting projects and skills.'),
  ('GitHub', 'github', 'Career Prep', 'Code hosting platform used for technical portfolios.'),
  ('Technical Writing', 'technical-writing', 'Communication', 'Explaining technical work in readable form.'),
  ('A/B Testing', 'ab-testing', 'Experimentation', 'Running and evaluating randomized controlled tests.'),
  ('Experimental Design', 'experimental-design', 'Experimentation', 'Designing experiments to isolate causal effects.'),
  ('Statistical Inference', 'statistical-inference', 'Math & Analytics', 'Drawing conclusions from sample data.'),
  ('Dashboard Design', 'dashboard-design', 'Visualization', 'Creating clean, insightful visual data summaries.');