-- Insert 10 career paths into career_paths table
INSERT INTO public.career_paths (
  title, summary, industry, level, average_salary, growth_outlook, 
  key_skills, education_required, certifications, common_entry_roles, advanced_roles
) VALUES
(
  'Software Engineer',
  'Design, develop, and maintain software applications and systems using various programming languages and frameworks',
  'Technology',
  'Entry',
  95000,
  'Much faster than average',
  ARRAY['JavaScript', 'Python', 'Git', 'Problem Solving', 'API Development', 'Database Design', 'Testing', 'Agile Methodologies'],
  'Bachelor''s in Computer Science or related field',
  ARRAY['AWS Certified Developer', 'Google Cloud Professional', 'Oracle Java Certification', 'Microsoft Azure Developer'],
  ARRAY['Junior Developer', 'Frontend Developer', 'Backend Developer', 'Full Stack Developer'],
  ARRAY['Senior Software Engineer', 'Tech Lead', 'Engineering Manager', 'Principal Engineer', 'Software Architect']
),
(
  'Data Analyst',
  'Collect, process, and analyze data to help organizations make informed business decisions',
  'Technology',
  'Entry',
  72000,
  'Much faster than average',
  ARRAY['SQL', 'Python', 'Excel', 'Data Visualization', 'Statistical Analysis', 'Tableau', 'Power BI', 'Critical Thinking'],
  'Bachelor''s in Statistics, Mathematics, or related field',
  ARRAY['Google Analytics', 'Tableau Desktop Specialist', 'Microsoft Power BI', 'SAS Certified Base Programmer'],
  ARRAY['Data Analyst', 'Business Analyst', 'Research Analyst', 'Reporting Analyst'],
  ARRAY['Senior Data Analyst', 'Data Scientist', 'Analytics Manager', 'Business Intelligence Manager']
),
(
  'UX Designer',
  'Research user needs and create intuitive, user-centered digital experiences and interfaces',
  'Design',
  'Entry',
  78000,
  'Faster than average',
  ARRAY['User Research', 'Wireframing', 'Prototyping', 'Figma', 'Adobe Creative Suite', 'Information Architecture', 'Usability Testing', 'Design Systems'],
  'Bachelor''s in Design, Psychology, or related field',
  ARRAY['Google UX Design Certificate', 'Nielsen Norman Group UX Certification', 'Adobe Certified Expert'],
  ARRAY['Junior UX Designer', 'UI Designer', 'Product Designer', 'Visual Designer'],
  ARRAY['Senior UX Designer', 'Lead UX Designer', 'UX Manager', 'Design Director', 'Head of Design']
),
(
  'Product Manager',
  'Define product strategy, coordinate development teams, and guide products from conception to launch',
  'Business',
  'Mid',
  115000,
  'Faster than average',
  ARRAY['Strategic Planning', 'Market Research', 'Agile Methodology', 'Data Analysis', 'Stakeholder Management', 'Roadmap Planning', 'A/B Testing', 'Communication'],
  'Bachelor''s in Business, Engineering, or related field',
  ARRAY['Certified Scrum Product Owner', 'Product Management Certificate', 'Google Analytics', 'Pragmatic Marketing'],
  ARRAY['Associate Product Manager', 'Business Analyst', 'Project Manager', 'Marketing Coordinator'],
  ARRAY['Senior Product Manager', 'Group Product Manager', 'Director of Product', 'VP of Product', 'Chief Product Officer']
),
(
  'Cybersecurity Analyst',
  'Monitor, detect, and respond to security threats while implementing protective measures for organizational systems',
  'Technology',
  'Entry',
  88000,
  'Much faster than average',
  ARRAY['Network Security', 'Incident Response', 'Risk Assessment', 'Security Tools', 'Vulnerability Assessment', 'Compliance', 'Forensics', 'Threat Intelligence'],
  'Bachelor''s in Cybersecurity, Computer Science, or related field',
  ARRAY['CompTIA Security+', 'CISSP', 'CISM', 'CEH', 'SANS GIAC'],
  ARRAY['Security Analyst', 'IT Security Specialist', 'Junior Cybersecurity Analyst', 'SOC Analyst'],
  ARRAY['Senior Security Analyst', 'Security Engineer', 'Security Manager', 'CISO', 'Security Consultant']
),
(
  'Registered Nurse',
  'Provide direct patient care, administer medications, and coordinate with healthcare teams in various medical settings',
  'Healthcare',
  'Entry',
  75000,
  'Much faster than average',
  ARRAY['Patient Care', 'Medical Knowledge', 'Critical Thinking', 'Communication', 'EMR Systems', 'Medication Administration', 'Patient Assessment', 'Teamwork'],
  'Associate or Bachelor''s in Nursing',
  ARRAY['RN License', 'BLS Certification', 'ACLS', 'Specialty Certifications', 'PALS'],
  ARRAY['Staff Nurse', 'Floor Nurse', 'Medical-Surgical Nurse', 'ICU Nurse'],
  ARRAY['Charge Nurse', 'Nurse Manager', 'Nurse Practitioner', 'Clinical Nurse Specialist', 'Director of Nursing']
),
(
  'Growth Marketing Manager',
  'Develop and execute data-driven marketing strategies to accelerate customer acquisition and business growth',
  'Business',
  'Mid',
  85000,
  'Faster than average',
  ARRAY['Digital Marketing', 'A/B Testing', 'Analytics', 'SEO/SEM', 'Content Marketing', 'Conversion Optimization', 'Customer Acquisition', 'Marketing Automation'],
  'Bachelor''s in Marketing, Business, or related field',
  ARRAY['Google Ads', 'HubSpot Marketing', 'Facebook Blueprint', 'Google Analytics', 'Marketo Certified'],
  ARRAY['Marketing Coordinator', 'Digital Marketing Specialist', 'Marketing Analyst', 'Content Marketer'],
  ARRAY['Senior Growth Manager', 'Head of Growth', 'Marketing Director', 'VP of Marketing', 'Chief Marketing Officer']
),
(
  'AI Prompt Engineer',
  'Design and optimize prompts for AI systems to achieve desired outputs and improve model performance',
  'Technology',
  'Entry',
  92000,
  'Much faster than average',
  ARRAY['Natural Language Processing', 'Machine Learning', 'Python', 'API Integration', 'Prompt Design', 'Model Fine-tuning', 'Data Analysis', 'Technical Writing'],
  'Bachelor''s in Computer Science, AI, or related field',
  ARRAY['OpenAI API Certification', 'Google AI Certification', 'AWS Machine Learning', 'Coursera AI Specialization'],
  ARRAY['Junior AI Engineer', 'ML Engineer', 'Prompt Designer', 'AI Research Assistant'],
  ARRAY['Senior AI Engineer', 'AI Product Manager', 'Machine Learning Lead', 'AI Research Scientist']
),
(
  'Brand Strategist',
  'Develop comprehensive brand positioning and messaging strategies to build strong market presence and customer loyalty',
  'Design',
  'Mid',
  82000,
  'Average',
  ARRAY['Brand Development', 'Market Research', 'Strategic Thinking', 'Creative Direction', 'Consumer Psychology', 'Competitive Analysis', 'Storytelling', 'Campaign Development'],
  'Bachelor''s in Marketing, Communications, or related field',
  ARRAY['Google Analytics', 'Facebook Blueprint', 'Brand Management Certificate', 'Digital Marketing Institute'],
  ARRAY['Marketing Coordinator', 'Brand Assistant', 'Marketing Analyst', 'Account Coordinator'],
  ARRAY['Senior Brand Manager', 'Brand Director', 'Head of Brand', 'Chief Brand Officer', 'Creative Director']
),
(
  'Operations Analyst',
  'Analyze business processes and workflows to identify inefficiencies and recommend improvements for operational excellence',
  'Business',
  'Entry',
  68000,
  'Faster than average',
  ARRAY['Process Analysis', 'Data Analysis', 'Excel', 'Project Management', 'Lean Six Sigma', 'Business Intelligence', 'SQL', 'Problem Solving'],
  'Bachelor''s in Business, Engineering, or related field',
  ARRAY['Six Sigma Green Belt', 'PMP', 'Lean Certification', 'Business Analysis Certificate'],
  ARRAY['Business Analyst', 'Operations Coordinator', 'Process Analyst', 'Data Analyst'],
  ARRAY['Senior Operations Analyst', 'Operations Manager', 'Director of Operations', 'VP of Operations']
);