-- Insert 10 additional career paths into career_paths table
INSERT INTO public.career_paths (
  title, summary, industry, level, average_salary, growth_outlook, 
  key_skills, education_required, certifications, common_entry_roles, advanced_roles
) VALUES
(
  'Cloud Solutions Architect',
  'Design scalable and secure cloud architectures tailored to organizational needs using platforms like AWS, Azure, or GCP.',
  'Technology',
  'Senior',
  140000,
  'Much faster than average',
  ARRAY['Cloud Architecture', 'Infrastructure as Code', 'DevOps', 'Security', 'Networking', 'AWS', 'Azure', 'GCP'],
  'Bachelor''s in Computer Science or IT',
  ARRAY['AWS Certified Solutions Architect', 'Microsoft Azure Solutions Architect', 'Google Professional Cloud Architect', 'Terraform Associate'],
  ARRAY['DevOps Engineer', 'Cloud Engineer', 'System Administrator', 'Software Engineer'],
  ARRAY['Principal Architect', 'Cloud Strategy Lead', 'CTO', 'Head of Infrastructure']
),
(
  'Financial Analyst',
  'Evaluate financial data and market trends to guide investment decisions and strategic planning.',
  'Finance',
  'Entry',
  68000,
  'Faster than average',
  ARRAY['Financial Modeling', 'Excel', 'Valuation', 'Forecasting', 'Data Analysis', 'Power BI', 'Investment Analysis'],
  'Bachelor''s in Finance, Economics, or Accounting',
  ARRAY['CFA', 'CPA', 'FMVA', 'Bloomberg Market Concepts'],
  ARRAY['Junior Analyst', 'Investment Analyst', 'Accounting Assistant', 'Budget Analyst'],
  ARRAY['Senior Financial Analyst', 'Finance Manager', 'Investment Manager', 'CFO']
),
(
  'DevOps Engineer',
  'Automate software deployment pipelines, improve CI/CD processes, and maintain scalable infrastructure systems.',
  'Technology',
  'Mid',
  105000,
  'Much faster than average',
  ARRAY['CI/CD', 'Containerization', 'Kubernetes', 'Terraform', 'Monitoring', 'Linux', 'Python', 'AWS'],
  'Bachelor''s in Computer Science or Engineering',
  ARRAY['Docker Certified Associate', 'CKA', 'AWS DevOps Engineer', 'Microsoft Azure DevOps'],
  ARRAY['SysAdmin', 'Software Engineer', 'Build Engineer', 'IT Operations Specialist'],
  ARRAY['Senior DevOps Engineer', 'Platform Engineer', 'Site Reliability Engineer', 'Infrastructure Lead']
),
(
  'Digital Product Designer',
  'Design and prototype digital interfaces with a focus on usability, brand coherence, and delightful user experiences.',
  'Design',
  'Mid',
  88000,
  'Faster than average',
  ARRAY['Figma', 'Sketch', 'UI Design', 'Prototyping', 'Interaction Design', 'Design Systems', 'UX Writing', 'Accessibility'],
  'Bachelor''s in Design, HCI, or related field',
  ARRAY['Google UX Design Certificate', 'Adobe Certified Expert', 'Design Thinking Practitioner'],
  ARRAY['UX Designer', 'Visual Designer', 'UI Designer', 'Product Designer'],
  ARRAY['Lead Product Designer', 'Design Manager', 'Head of Design', 'Creative Director']
),
(
  'AI/ML Research Scientist',
  'Conduct original research and develop new machine learning models for applications in various industries.',
  'Technology',
  'Advanced',
  155000,
  'Much faster than average',
  ARRAY['Deep Learning', 'NLP', 'TensorFlow', 'PyTorch', 'Data Science', 'Python', 'Mathematics', 'Research'],
  'PhD in Computer Science, AI, or related field',
  ARRAY['DeepLearning.AI Specialization', 'Google ML Crash Course', 'MIT AI Certification'],
  ARRAY['ML Engineer', 'Data Scientist', 'Research Assistant', 'AI Engineer'],
  ARRAY['Senior Research Scientist', 'AI Lab Director', 'Chief AI Scientist']
),
(
  'Human Resources Business Partner (HRBP)',
  'Align HR strategies with business goals and support organizational development, talent, and employee engagement.',
  'Business',
  'Mid',
  90000,
  'Average',
  ARRAY['Talent Management', 'HR Strategy', 'Performance Management', 'Conflict Resolution', 'Compensation', 'Recruitment', 'Labor Law'],
  'Bachelor''s in Human Resources or Business',
  ARRAY['SHRM-CP', 'PHR', 'HR Analytics Certificate', 'Compensation Management Certification'],
  ARRAY['HR Generalist', 'Recruiter', 'HR Coordinator', 'Training Specialist'],
  ARRAY['HR Manager', 'Director of HR', 'VP of People', 'Chief People Officer']
),
(
  'SaaS Sales Executive',
  'Sell cloud-based software solutions to businesses by identifying needs, closing deals, and managing client accounts.',
  'Sales',
  'Mid',
  95000,
  'Faster than average',
  ARRAY['B2B Sales', 'CRM', 'Solution Selling', 'Demoing', 'Negotiation', 'Lead Qualification', 'Pipeline Management'],
  'Bachelor''s in Business, Marketing, or related field',
  ARRAY['HubSpot Sales', 'MEDDIC Certification', 'Sandler Sales', 'Challenger Sales Training'],
  ARRAY['Sales Development Rep', 'Account Executive', 'Inside Sales Rep', 'Customer Success Associate'],
  ARRAY['Enterprise AE', 'Sales Manager', 'Director of Sales', 'VP of Sales', 'Chief Revenue Officer']
),
(
  'Environmental Scientist',
  'Investigate environmental issues, conduct field research, and develop solutions to protect natural resources.',
  'Science',
  'Entry',
  70000,
  'Faster than average',
  ARRAY['Field Research', 'Data Analysis', 'Environmental Policy', 'Report Writing', 'GIS', 'Risk Assessment', 'Lab Techniques'],
  'Bachelor''s in Environmental Science or related field',
  ARRAY['Certified Environmental Scientist', 'GIS Certification', 'LEED Green Associate'],
  ARRAY['Field Technician', 'Lab Assistant', 'Research Analyst', 'Environmental Consultant'],
  ARRAY['Senior Environmental Scientist', 'Project Manager', 'Sustainability Director', 'Policy Advisor']
),
(
  'Mobile App Developer',
  'Build and maintain native or cross-platform mobile apps for Android and iOS devices using modern frameworks.',
  'Technology',
  'Entry',
  90000,
  'Much faster than average',
  ARRAY['React Native', 'Swift', 'Kotlin', 'UI Design', 'Mobile APIs', 'Version Control', 'Performance Optimization', 'Cross-platform Development'],
  'Bachelor''s in Computer Science or Software Engineering',
  ARRAY['Google Associate Android Developer', 'Apple Certified iOS Developer', 'React Native Certification'],
  ARRAY['Mobile Developer', 'iOS Developer', 'Android Developer', 'App Engineer'],
  ARRAY['Lead Mobile Engineer', 'Mobile Architect', 'Head of Mobile', 'Mobile Product Manager']
),
(
  'Sustainability Consultant',
  'Advise organizations on implementing sustainable practices to reduce environmental impact and improve ESG scores.',
  'Consulting',
  'Mid',
  87000,
  'Faster than average',
  ARRAY['Sustainability Auditing', 'ESG Reporting', 'Carbon Accounting', 'Stakeholder Engagement', 'Environmental Compliance', 'Green Supply Chain'],
  'Bachelor''s or Master''s in Sustainability, Environmental Science, or Business',
  ARRAY['LEED AP', 'GRESB', 'GRI Certified', 'Certified Energy Manager'],
  ARRAY['Sustainability Analyst', 'Environmental Consultant', 'ESG Intern', 'Research Associate'],
  ARRAY['Sustainability Lead', 'ESG Director', 'VP of Sustainability', 'Chief Sustainability Officer']
);