-- Insert batch 3 of 10 career paths into career_paths table
INSERT INTO public.career_paths (
  title, summary, industry, level, average_salary, growth_outlook, 
  key_skills, education_required, certifications, common_entry_roles, advanced_roles
) VALUES
(
  'Digital Project Manager',
  'Coordinate and manage digital projects across design, development, and marketing teams to deliver on time and on budget.',
  'Business',
  'Mid',
  85000,
  'Faster than average',
  ARRAY['Agile', 'Scrum', 'Project Planning', 'Team Communication', 'Budget Management', 'Jira', 'Trello', 'Risk Management'],
  'Bachelor''s in Business, IT, or related field',
  ARRAY['PMP', 'Certified ScrumMaster', 'AgilePM', 'Google Project Management Certificate'],
  ARRAY['Project Coordinator', 'Scrum Master', 'Marketing Project Manager', 'Operations Coordinator'],
  ARRAY['Senior PM', 'Program Manager', 'Director of Delivery', 'Head of Projects']
),
(
  'Instructional Designer',
  'Create engaging educational content and learning experiences for academic or corporate training settings.',
  'Education',
  'Mid',
  78000,
  'Faster than average',
  ARRAY['Curriculum Design', 'eLearning Development', 'Instructional Design', 'Storyboarding', 'LMS', 'Articulate 360', 'Captivate', 'Assessment Design'],
  'Bachelor''s or Master''s in Instructional Design, Education, or Learning Technologies',
  ARRAY['ATD Certification', 'Instructional Design Pro', 'eLearning Guild Certificate'],
  ARRAY['Training Coordinator', 'Content Developer', 'Learning Specialist', 'eLearning Designer'],
  ARRAY['Senior Instructional Designer', 'Learning Experience Designer', 'Director of L&D', 'Chief Learning Officer']
),
(
  'Blockchain Developer',
  'Build decentralized applications (dApps), smart contracts, and secure blockchain infrastructure.',
  'Technology',
  'Advanced',
  125000,
  'Faster than average',
  ARRAY['Solidity', 'Smart Contracts', 'Ethereum', 'Cryptography', 'Web3.js', 'Rust', 'Blockchain Architecture', 'DeFi'],
  'Bachelor''s in Computer Science or related field',
  ARRAY['Ethereum Developer Certificate', 'Certified Blockchain Developer', 'Blockchain Council Certifications'],
  ARRAY['Smart Contract Developer', 'Web3 Developer', 'Crypto Engineer', 'Backend Developer'],
  ARRAY['Blockchain Architect', 'Protocol Engineer', 'Head of Web3 Engineering', 'CTO']
),
(
  'Technical Recruiter',
  'Source, assess, and hire technical talent for engineering, design, and product teams.',
  'Human Resources',
  'Entry',
  68000,
  'Faster than average',
  ARRAY['Technical Sourcing', 'ATS Systems', 'Interviewing', 'Negotiation', 'Networking', 'Boolean Search', 'Employer Branding', 'Stakeholder Management'],
  'Bachelor''s in Business, HR, or Psychology',
  ARRAY['LinkedIn Certified Recruiter', 'Tech Recruitment Certificate', 'SHRM-CP'],
  ARRAY['Recruiting Coordinator', 'Talent Sourcer', 'HR Assistant', 'Campus Recruiter'],
  ARRAY['Senior Tech Recruiter', 'Recruiting Manager', 'Director of Talent Acquisition', 'VP of People']
),
(
  'Digital Illustrator',
  'Create visual assets for books, games, media, branding, and web using digital tools and artistic techniques.',
  'Creative',
  'Freelance',
  60000,
  'Steady',
  ARRAY['Digital Painting', 'Photoshop', 'Illustrator', 'Procreate', 'Character Design', 'Concept Art', 'Storyboarding', 'Visual Storytelling'],
  'Bachelor''s in Fine Arts, Illustration, or Design (optional)',
  ARRAY['Adobe Certified Expert', 'Visual Development Certificate', 'Skillshare/ArtStation Masterclasses'],
  ARRAY['Freelance Artist', 'Junior Illustrator', 'Concept Artist', 'Design Assistant'],
  ARRAY['Lead Illustrator', 'Art Director', 'Visual Designer', 'Creative Director']
),
(
  'Healthcare Administrator',
  'Oversee healthcare facility operations, ensure compliance, and manage teams and budgets.',
  'Healthcare',
  'Mid',
  94000,
  'Faster than average',
  ARRAY['Healthcare Policy', 'Budgeting', 'Team Management', 'EMR Systems', 'Compliance', 'Operations Management', 'Quality Control'],
  'Bachelor''s or Master''s in Healthcare Admin, Public Health, or Business',
  ARRAY['FACHE', 'Certified Healthcare Admin', 'Healthcare Compliance Certificate'],
  ARRAY['Medical Office Manager', 'Operations Analyst', 'Practice Coordinator', 'Patient Services Lead'],
  ARRAY['Clinic Director', 'Hospital Administrator', 'VP of Operations', 'Chief Administrative Officer']
),
(
  'Freelance Copywriter',
  'Write persuasive content for ads, websites, social media, and brand messaging in freelance or agency settings.',
  'Marketing',
  'Freelance',
  65000,
  'Steady',
  ARRAY['SEO Writing', 'Email Marketing', 'Sales Copy', 'Tone & Voice', 'Grammar', 'Content Strategy', 'Persuasion', 'Headline Writing'],
  'Bachelor''s in English, Communications, or Marketing (optional)',
  ARRAY['Copy School', 'HubSpot Content Marketing', 'AWAI Copywriting Certification'],
  ARRAY['Content Writer', 'Social Media Writer', 'SEO Blogger', 'Ghostwriter'],
  ARRAY['Senior Copywriter', 'Content Strategist', 'Creative Lead', 'Brand Voice Director']
),
(
  'Supply Chain Analyst',
  'Optimize logistics, inventory, procurement, and vendor relationships for efficient supply chain performance.',
  'Logistics',
  'Mid',
  81000,
  'Average',
  ARRAY['Supply Chain Management', 'ERP Systems', 'Forecasting', 'Inventory Management', 'Excel', 'Data Analytics', 'Logistics'],
  'Bachelor''s in Supply Chain, Operations, or Engineering',
  ARRAY['APICS CPIM', 'CSCP', 'SCPro', 'Six Sigma'],
  ARRAY['Logistics Coordinator', 'Procurement Analyst', 'Operations Associate', 'Warehouse Analyst'],
  ARRAY['Supply Chain Manager', 'Director of Logistics', 'Procurement Lead', 'VP of Supply Chain']
),
(
  'eCommerce Manager',
  'Manage online store operations, optimize digital funnels, and increase sales through conversion strategies.',
  'Business',
  'Mid',
  89000,
  'Faster than average',
  ARRAY['Shopify', 'Amazon FBA', 'Analytics', 'A/B Testing', 'Product Merchandising', 'UX', 'Email Automation', 'Conversion Rate Optimization'],
  'Bachelor''s in Business, Marketing, or related field',
  ARRAY['Google Analytics', 'Facebook Ads', 'Klaviyo Certification', 'Shopify Partner Training'],
  ARRAY['Online Store Coordinator', 'Product Lister', 'Email Marketer', 'Growth Specialist'],
  ARRAY['Head of eCommerce', 'Digital Director', 'VP of Online Sales', 'Chief Digital Officer']
),
(
  'Legal Operations Manager',
  'Support in-house legal teams by optimizing workflows, budgeting, and vendor management to improve legal efficiency.',
  'Legal',
  'Mid',
  97000,
  'Faster than average',
  ARRAY['Contract Management', 'Compliance', 'Process Optimization', 'Legal Tech', 'Vendor Management', 'Budgeting', 'eBilling'],
  'Bachelor''s in Legal Studies, Business, or related field',
  ARRAY['Legal Ops Certification', 'CLM (Contract Lifecycle Management)', 'Lean Six Sigma Legal'],
  ARRAY['Legal Assistant', 'Contracts Coordinator', 'Paralegal', 'Operations Analyst'],
  ARRAY['Director of Legal Ops', 'VP of Legal Strategy', 'Chief Legal Officer']
);