-- Insert final 10 career paths into career_paths table
INSERT INTO public.career_paths (
  title, summary, industry, level, average_salary, growth_outlook,
  key_skills, education_required, certifications, common_entry_roles, advanced_roles
) VALUES
(
  'Electric Vehicle Technician',
  'Maintains and repairs electric vehicles and charging systems, supporting the growth of clean transportation.',
  'Green Energy',
  'Entry',
  63000,
  'Much faster than average',
  ARRAY['Diagnostics', 'Battery Systems', 'Electrical Systems', 'Mechanical Repair', 'Charging Stations', 'Safety Procedures'],
  'Associate Degree or Technical Certification in Automotive Technology',
  ARRAY['ASE Electric Vehicle Certification', 'EV Pro+ Certification', 'Automotive Service Excellence (ASE)'],
  ARRAY['EV Technician', 'Automotive Technician', 'Shop Assistant', 'Charging Station Installer'],
  ARRAY['Master EV Technician', 'EV Service Manager', 'Fleet Maintenance Manager', 'Technical Instructor']
),
(
  'Climate Risk Analyst',
  'Evaluates environmental, financial, and regulatory risks due to climate change, helping companies make resilient decisions.',
  'Environmental Science',
  'Mid',
  91000,
  'Faster than average',
  ARRAY['Data Modeling', 'Sustainability Reporting', 'GIS', 'Risk Assessment', 'Climate Policy', 'Financial Analysis'],
  'Bachelor''s or Master''s in Environmental Science, Finance, or Climate Policy',
  ARRAY['TCFD Certification', 'SASB Fundamentals', 'CFA ESG Certification'],
  ARRAY['Sustainability Analyst', 'Policy Analyst', 'ESG Analyst', 'Research Associate'],
  ARRAY['Senior Climate Analyst', 'ESG Director', 'Chief Sustainability Officer']
),
(
  'Esports Program Manager',
  'Plans and runs competitive gaming tournaments, partnerships, and player development programs in the esports industry.',
  'Entertainment & Media',
  'Mid',
  78000,
  'Faster than average',
  ARRAY['Project Management', 'Team Coordination', 'Event Planning', 'Sponsorships', 'Streaming Platforms', 'Marketing'],
  'Bachelor''s in Communications, Business, or Game Design',
  ARRAY['Project Management Certification', 'Twitch Affiliate Program', 'Esports Management Certificate'],
  ARRAY['Esports Coordinator', 'Tournament Organizer', 'Content Manager', 'Gaming Community Lead'],
  ARRAY['Director of Esports', 'Gaming Partnerships Manager', 'VP of Player Development']
),
(
  'Generative AI Designer',
  'Uses AI tools to create images, animations, interfaces, and storyboards for content, marketing, and product teams.',
  'Technology',
  'Entry',
  85000,
  'Much faster than average',
  ARRAY['Prompt Design', 'Midjourney', 'Runway ML', 'Figma', 'Creative Direction', 'Visual Storytelling'],
  'Bachelor''s in Design, Art, or Computer Science (or portfolio-based entry)',
  ARRAY['AI for Creatives Certificate', 'Runway ML Creator Badge', 'Midjourney Pro Tips', 'Figma Certification'],
  ARRAY['AI Art Creator', 'Junior Product Designer', 'Content Creator', 'Visual Designer'],
  ARRAY['Generative Art Director', 'Senior AI Designer', 'Creative Technologist']
),
(
  'Career Coach',
  'Guides clients through career transitions, resume building, interviewing, and goal-setting for professional growth.',
  'Education & Coaching',
  'Mid',
  68000,
  'Average',
  ARRAY['Career Assessment', 'Resume Writing', 'Interview Prep', 'Coaching', 'Goal Setting', 'LinkedIn Optimization'],
  'Bachelor''s in Psychology, Counseling, or HR',
  ARRAY['Certified Career Coach (CCE)', 'ICF Coaching Certification', 'LinkedIn Learning Coach Badge'],
  ARRAY['Career Advisor', 'Job Search Coach', 'Resume Consultant', 'HR Associate'],
  ARRAY['Senior Career Coach', 'Career Program Director', 'Coaching Practice Owner']
),
(
  'Solar Energy Technician',
  'Installs, maintains, and troubleshoots residential and commercial solar photovoltaic systems.',
  'Green Energy',
  'Entry',
  57000,
  'Much faster than average',
  ARRAY['Electrical Wiring', 'Solar Panel Installation', 'Roofing Safety', 'System Troubleshooting', 'Inverter Configuration'],
  'Technical Certificate or Associate Degree in Solar Energy or Electrical Technology',
  ARRAY['NABCEP PV Installation Professional', 'OSHA 30', 'SolarEdge Certification'],
  ARRAY['Solar Installer', 'Rooftop Technician', 'Electrical Helper', 'Field Service Tech'],
  ARRAY['Lead Installer', 'Solar Project Foreman', 'Field Operations Manager']
),
(
  'Voice User Interface (VUI) Designer',
  'Designs conversational flows and voice interactions for products like smart speakers, virtual assistants, and IVR systems.',
  'Design',
  'Mid',
  96000,
  'Faster than average',
  ARRAY['Conversational Design', 'Voice Scripting', 'User Research', 'Speech UX', 'Dialog Management', 'Prototyping'],
  'Bachelor''s in Linguistics, HCI, or UX Design',
  ARRAY['Voice UX Design Certificate', 'Google Dialogflow', 'Amazon Alexa Skills Certification'],
  ARRAY['UX Designer', 'Content Designer', 'Script Writer', 'Conversation Designer'],
  ARRAY['VUI Lead', 'Design Manager - Voice Products', 'Conversational AI Strategist']
),
(
  'CNC Machine Programmer',
  'Programs and operates computer-controlled equipment for high-precision parts used in aerospace, automotive, and manufacturing.',
  'Manufacturing',
  'Entry',
  62000,
  'Average',
  ARRAY['G-Code Programming', 'Blueprint Reading', 'CAD/CAM', 'Toolpath Optimization', 'Machine Operation', 'Safety Standards'],
  'Technical School or Apprenticeship in CNC Machining',
  ARRAY['NIMS CNC Programming Certification', 'Mastercam Certification', 'OSHA 10'],
  ARRAY['CNC Operator', 'Machinist Apprentice', 'Manufacturing Technician'],
  ARRAY['Senior CNC Programmer', 'Manufacturing Engineer', 'Production Supervisor']
),
(
  'YouTube Channel Strategist',
  'Plans and executes content calendars, growth tactics, and monetization strategies for creators and brands on YouTube.',
  'Media & Content',
  'Mid',
  79000,
  'Faster than average',
  ARRAY['SEO for Video', 'Content Strategy', 'YouTube Analytics', 'Thumbnail Optimization', 'Monetization', 'Community Engagement'],
  'Bachelor''s in Media, Marketing, or Communications (or creator experience)',
  ARRAY['YouTube Certified', 'HubSpot Content Strategy', 'Google Video Ads Certification'],
  ARRAY['Content Manager', 'Video Editor', 'YouTube Assistant', 'Social Media Coordinator'],
  ARRAY['Channel Growth Manager', 'Digital Content Director', 'Creative Producer']
),
(
  'Cybersecurity Compliance Specialist',
  'Ensures that organizations follow data privacy and cybersecurity regulations like GDPR, HIPAA, and SOC 2.',
  'Technology',
  'Mid',
  98000,
  'Much faster than average',
  ARRAY['Risk Management', 'Compliance Frameworks', 'Audit Prep', 'Policy Writing', 'Security Controls', 'Legal Standards'],
  'Bachelor''s in Cybersecurity, Law, or IT Compliance',
  ARRAY['CISSP', 'CISA', 'HIPAA Compliance Officer', 'SOC 2 Readiness Certification'],
  ARRAY['Compliance Analyst', 'Security Associate', 'IT Auditor'],
  ARRAY['Compliance Lead', 'Cybersecurity Compliance Manager', 'Director of Governance, Risk, and Compliance']
);