INSERT INTO edu_courses (institution_code, code, code_norm, title, credits, level_year, source_url)
VALUES
  ('EXCELSIOR', 'ACC 211', 'acc211', 'Financial Accounting', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ACC 212', 'acc212', 'Managerial Accounting', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ACC 314', 'acc314', 'Intermediate Accounting I', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ACC 315', 'acc315', 'Intermediate Accounting II', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ACC 360', 'acc360', 'Cost Accounting', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ACC 400', 'acc400', 'Auditing', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ACC 415', 'acc415', 'Advanced Financial Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ACC 417', 'acc417', 'Individual and Corporate Taxation', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ACC 504', 'acc504', 'Corporate Financial Reporting and Disclosure', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ACC 505', 'acc505', 'Financial Statement Analysis', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ADR 671', 'adr671', 'Mediation', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ART 102', 'art102', 'History of Western Art Since the 15th Century', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BIO 110', 'bio110', 'Biology (Non-Lab)', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BIO 111', 'bio111', 'Biology Laboratory', 1, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BIO 115', 'bio115', 'Anatomy and Physiology I (Non Lab)', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BIO 115L', 'bio115l', 'Anatomy and Physiology I Lab', 1, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BIO 116', 'bio116', 'Anatomy and Physiology II (Non Lab)', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BIO 116L', 'bio116l', 'Anatomy and Physiology II Lab', 1, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BIO 212', 'bio212', 'Microbiology', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BIO 213', 'bio213', 'Pathophysiology', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BIO 340', 'bio340', 'Biodiversity', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 222', 'bus222', 'Business Communication', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 225', 'bus225', 'Consumer Behaviors', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 230', 'bus230', 'Business Law', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 231', 'bus231', 'Business Data Literacy', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 235', 'bus235', 'Financial Markets and Institutions', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 299', 'bus299', 'Business and Management Capstone', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 300', 'bus300', 'Introduction to Entrepreneurship', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 311', 'bus311', 'Organizational Behavior', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 312', 'bus312', 'Managing Human Resources', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 315', 'bus315', 'Labor Relations', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 323', 'bus323', 'Business Ethics', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 325', 'bus325', 'Women in Business', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 341', 'bus341', 'Management Concepts and Applications', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 343', 'bus343', 'International Marketing', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 350', 'bus350', 'Principles of Finance', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 351', 'bus351', 'Marketing Concepts and Application', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 352', 'bus352', 'Digital Marketing Fundamentals', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 375', 'bus375', 'Marketing Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 380', 'bus380', 'Managing Diversity in the Workplace', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 381', 'bus381', 'Transportation, Warehousing, and Distribution', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 425', 'bus425', 'Operations Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 431', 'bus431', 'Business Data Analysis', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 435', 'bus435', 'International Business', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 437', 'bus437', 'Securities Analysis', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 440', 'bus440', 'Business Supply Chain Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 443', 'bus443', 'Lean Logistics', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 452', 'bus452', 'Business Leadership', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 453', 'bus453', 'Recruitment and Selection', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 454', 'bus454', 'HR Analytics', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 460', 'bus460', 'Market Research', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 490', 'bus490', 'Integrated Business and Management Assessment BPB', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 499', 'bus499', 'Strategic Management Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 500', 'bus500', 'Accounting for Managers', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 501', 'bus501', 'Business Communications', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 502', 'bus502', 'Global Business Environment', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 504', 'bus504', 'Human Resource Management', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 506', 'bus506', 'Marketing', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 509', 'bus509', 'Resilient Leadership and Organizational Behavior', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 512', 'bus512', 'Compensation and Benefits', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 514', 'bus514', 'Employment Law', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 515', 'bus515', 'Labor Relations and Conflict Resolution', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 516', 'bus516', 'Communication Strategy for the Health Care Leader', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 517', 'bus517', 'Employee Staffing and Development', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 519', 'bus519', 'Training and Career Development', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 521', 'bus521', 'Operations and Project Management', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 524', 'bus524', 'Corporate Finance and Accounting', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 526', 'bus526', 'Strategic Management of Health Care Organizations', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 530', 'bus530', 'Project Management Principles and Application', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 532', 'bus532', 'Ethical Risk Management and Compliance', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 540', 'bus540', 'Strategic Management of Innovative Technology', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 545', 'bus545', 'Social Media Marketing', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 550', 'bus550', 'Contingency Planning', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 552', 'bus552', 'Leadership', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 553', 'bus553', 'Organizational Behavior', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 554', 'bus554', 'Change Management', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 561', 'bus561', 'Virtual Training and Development', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 562', 'bus562', 'Virtual Team Management', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 563', 'bus563', 'Data Analytics', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 564', 'bus564', 'Big Data and Visualization', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 570', 'bus570', 'Information Technology', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 573', 'bus573', 'Strategic Brand Marketing', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 591', 'bus591', 'Ai for Business', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 596', 'bus596', 'Strategy & Entrepreneurial Innovation', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 671', 'bus671', 'Mediation', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 696', 'bus696', 'Organizational Leadership, Technology, and Analytics Capstone', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 697', 'bus697', 'Human Resource Management, Diversity and Technology Capstone', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 698', 'bus698', 'MSM Capstone', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BUS 699', 'bus699', 'MBA Business Strategy Capstone', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CBC 600', 'cbc600', 'Implications of Legalization of Cannabis: Policy and Compliance', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CBC 601', 'cbc601', 'Complexities of Cannabis As Commerce', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CBC 602', 'cbc602', 'Risk Assessment in Cannabis Control', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CHE 101', 'che101', 'General Chemistry I', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CHE 101L', 'che101l', 'General Chemistry Laboratory I', 1, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'COMM 125', 'comm125', 'Public Speaking', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'COMM 210', 'comm210', 'Interpersonal Communication', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'COMM 423', 'comm423', 'Leadership and Team Building', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'COMM 423JF', 'comm423jf', 'Leadership and Team Building', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 311', 'cs311', 'Software Design and Architecture', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 313', 'cs313', 'Software Requirements Engineering and Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 315', 'cs315', 'Self-Reliant Language Learning', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 330', 'cs330', 'Data Structures, Algorithms, and Their Societal Impact', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 401', 'cs401', 'Theory of Computation and Computational Ethics', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 405', 'cs405', 'Human-Computer Interaction (Hci): Ai Integration and Social Impact', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 411', 'cs411', 'Software Project Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 415', 'cs415', 'Software Testing and Quality Assurance', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 417', 'cs417', 'Software Engineering and Practice', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 419', 'cs419', 'Software Maintenance and Evolution', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CS 495', 'cs495', 'Computer Science Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 101', 'cj101', 'Introduction to Criminal Justice', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 110', 'cj110', 'Introduction to Law Enforcement', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 120', 'cj120', 'Introduction to Corrections', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 228', 'cj228', 'Multicultural Issues in Criminal Justice', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 265', 'cj265', 'Criminal Procedure and Evidence', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 298', 'cj298', 'Criminal Justice Capstone (Associate''s Degree)', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 301', 'cj301', 'Juvenile Delinquency and Justice', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 315', 'cj315', 'Gangs in America', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 324', 'cj324', 'Criminology', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 330', 'cj330', 'Judicial Process', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 338', 'cj338', 'Criminal Justice Administration', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 365', 'cj365', 'Police and the Community', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 380', 'cj380', 'Ethics in Criminal Justice', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 432', 'cj432', 'Drugs and Crime', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CJ 498', 'cj498', 'Criminal Justice Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 511', 'mcj511', 'Public Budgeting and Financial Management', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 518', 'mcj518', 'Comparative Justice', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 522', 'mcj522', 'The Pillars of Criminal Justice', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 530', 'mcj530', 'Legal and Constitutional Law Issues in Criminal Justice', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 626', 'mcj626', 'Overview of Justice Administration', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 630', 'mcj630', 'Risk Assessment in Homeland Security', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 650', 'mcj650', 'Terrorism and Counterterrorism', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 651', 'mcj651', 'Overview of Homeland Security and Emergency Management', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 652', 'mcj652', 'Mental Health Issues in Criminal Justice', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 660', 'mcj660', 'Human Trafficking', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MCJ 698', 'mcj698', 'MCJ Capstone', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 220', 'cys220', 'Cloud Computing and Virtualization', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 245', 'cys245', 'Introduction to Cybersecurity', 1, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 260', 'cys260', 'Governance Legal and Compliance', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 345', 'cys345', 'Cybersecurity Defense in Depth', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 350', 'cys350', 'Cybersecurity Defense in Depth for the Nuclear Industry', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 400', 'cys400', 'Reverse Engineering', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 401', 'cys401', 'Organizational Information Security', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 403', 'cys403', 'Network and Application Security', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 426', 'cys426', 'Cyber Attacks and Defenses', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 450', 'cys450', 'Security Focused Risk Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 455', 'cys455', 'Business Continuity', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 456', 'cys456', 'Securing Mobile and Cloud Computing Environments', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 465', 'cys465', 'Cybersecurity Investigation and Case Studies for the Nuclear Industry', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 470', 'cys470', 'Secure Software Development', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 475', 'cys475', 'Large Scale Cybercrime and Terrorism', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 496', 'cys496', 'Cybersecurity Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 500', 'cys500', 'Foundations of Cybersecurity', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 504', 'cys504', 'Network and Communication Security', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 523', 'cys523', 'Software and Application Security', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 526', 'cys526', 'Cyber Attacks and Defense', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 540', 'cys540', 'Strategic Management of Innovative Technology', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 550', 'cys550', 'Cybersecurity Leadership', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 555', 'cys555', 'Cybersecurity Risk Management', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 560', 'cys560', 'Digital Forensics and Incident Response', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 565', 'cys565', 'Offensive Security', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 570', 'cys570', 'Information Assurance Engineering', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 596', 'cys596', 'Capstone Project in Cybersecurity', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'CYS 610', 'cys610', 'Cloud Technologies and Data Security', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ECO 260', 'eco260', 'Introduction to Microeconomics', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ECO 262', 'eco262', 'Introduction to Macroeconomics', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 152', 'elec152', 'Circuit Theory I', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 153', 'elec153', 'Circuit Theory II', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 160', 'elec160', 'Electronics I', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 161', 'elec161', 'Electronics II', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 199', 'elec199', 'Special Topics', 2, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 201', 'elec201', 'Digital Electronics', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 202', 'elec202', 'Microprocessors', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 210', 'elec210', 'Programmable Logic Controllers', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 306', 'elec306', 'Advanced Digital Design', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 307', 'elec307', 'Microcontrollers', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 321', 'elec321', 'Control Systems', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 331', 'elec331', 'Digital and Analog Communications', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 345', 'elec345', 'Electric Machines', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 350', 'elec350', 'Power Electronics', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 360', 'elec360', 'Generation and Transmission of Electric Power', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 370', 'elec370', 'Instrumentation and Data Acquisition', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ELEC 495', 'elec495', 'Integrated Technology Assessment BEL', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'EGR 210', 'egr210', 'Introduction to Engineering Analysis', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'EGR 280', 'egr280', 'Introduction to 3-D Modeling', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'EGR 290', 'egr290', 'Advanced 3-D Modeling', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ENG 101', 'eng101', 'English Composition', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ENG 101A', 'eng101a', 'Advanced Composition', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ENG 102', 'eng102', 'Composition II', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'ENG 102A', 'eng102a', 'Advanced Composition II', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'GEOL 108', 'geol108', 'Earth Science and Society', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 112', 'hsc112', 'Medical Terminology', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 121', 'hsc121', 'Health Care in the United States', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 124', 'hsc124', 'Professionalism in Health Care', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 292', 'hsc292', 'Associate in Health Sciences Capstone', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 302', 'hsc302', 'Principles of Health Care Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 305', 'hsc305', 'Critical Issues in Health Care Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 310', 'hsc310', 'Writing and Communication in the Health Science Professions', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 312', 'hsc312', 'Ethics of Health Care', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 320', 'hsc320', 'Health Care Issues in Culturally Diverse Populations', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 330', 'hsc330', 'Legal and Regulatory Environment of Health Care', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 375', 'hsc375', 'Health and Wellness', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 402', 'hsc402', 'Managing Stress', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 403', 'hsc403', 'Nutrition for Wellness', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 414', 'hsc414', 'Budget and Finance in Health Care Organizations', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 432', 'hsc432', 'Introduction to the Health Care Delivery System', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 445', 'hsc445', 'Introduction to Health Care Informatics', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 450', 'hsc450', 'Economics of Health Care', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 464', 'hsc464', 'Health Sciences Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 470', 'hsc470', 'Healthcare Management Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 510', 'hsc510', 'Health Care Policy, Politics and Power', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 516', 'hsc516', 'Communication Strategy for the Health Care Leader', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 517', 'hsc517', 'Contemporary Issues in Health Care Delivery Systems', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 525', 'hsc525', 'Informatics for the Healthcare Leader', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 526', 'hsc526', 'Strategic Management of Health Care Organizations', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 528', 'hsc528', 'Health Care Finance', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 561', 'hsc561', 'Quality Management in Health Care', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 644', 'hsc644', 'Nutrition Science for Health Professionals', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 645', 'hsc645', 'Nutrition Across the Life Cycle', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 646', 'hsc646', 'Health Education: A Cross-Cultural Perspective', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 697', 'hsc697', 'Graduate Health Sciences Capstone', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HSC 698', 'hsc698', 'MS in Health Care Administration Capstone', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HIS 101', 'his101', 'United States History I', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HIS 102', 'his102', 'United States History II', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HIS 120', 'his120', 'World History I', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HIS 335', 'his335', 'United States Civil War', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HIS 350', 'his350', 'World War I', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HEM 125', 'hem125', 'Introduction to Homeland Security', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HEM 350', 'hem350', 'International Terrorism', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HEM 352', 'hem352', 'Domestic Terrorism', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HEM 356', 'hem356', 'Emergency Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HEM 450', 'hem450', 'Counterterrorism', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HEM 460', 'hem460', 'Infrastructure Security and Policy', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HEM 498', 'hem498', 'Homeland Security and Emergency Management Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HUM 253', 'hum253', 'Mythology', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HUM 306', 'hum306', 'Creative Problem Solving', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HUM 306JF', 'hum306jf', 'Creative Problem Solving', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HUM 307', 'hum307', 'Critical Thinking', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HUM 307JF', 'hum307jf', 'Critical Thinking', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'HUM 321', 'hum321', 'I Feel Your Pain: Illness and Empathy in the Arts', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'INL 102', 'inl102', 'Information Literacy', 1, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 200', 'it200', 'Hardware and Software Essentials', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 211', 'it211', 'Fundamentals of Programming', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 221', 'it221', 'Introduction to Computers', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 250', 'it250', 'Business Data Communications', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 313', 'it313', 'Intermediate Programming', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 321', 'it321', 'Computer Systems Architecture', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 360', 'it360', 'Operating Systems', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 370', 'it370', 'Database Management Systems', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 371', 'it371', 'Web Design and Development', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 375', 'it375', 'Human Computer Interactive Design', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 380', 'it380', 'Overview of Computer Security', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 390', 'it390', 'Project Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 406', 'it406', 'Computer Forensics', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 422', 'it422', 'Advanced Networking', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 424', 'it424', 'Network Operating Systems', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 426', 'it426', 'Wireless Technology', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 428', 'it428', 'Telecommunications Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 430', 'it430', 'Network System Design and Management', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 460', 'it460', 'System Administration', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IT 495', 'it495', 'Integrated Technology Assessment BIX', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IND 101', 'ind101', 'Cornerstone A: Foundations', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IND 101JF', 'ind101jf', 'Cornerstone A: Foundations', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IND 203', 'ind203', 'Introduction to Professional Ethics', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IND 301', 'ind301', 'Cornerstone B: Pathways', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IND 301JF', 'ind301jf', 'Cornerstone B: Pathways', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IND 501', 'ind501', 'An Interdisciplinary Approach to Ethical Leadership', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IND 502', 'ind502', 'Strategic Talent Management in A Complex World', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IND 503', 'ind503', 'Data Driven Decision Making', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'IND 522', 'ind522', 'Leading High Performing Teams', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'LA 298', 'la298', 'Associate Degree Capstone', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'LA 498', 'la498', 'Liberal Arts Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'LA 498HIS', 'la498his', 'History Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'LA 498JF', 'la498jf', 'Liberal Arts Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'LA 498NS', 'la498ns', 'Natural Science Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'LA 498PSY', 'la498psy', 'Psychology Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'LA 498SS', 'la498ss', 'Social Science Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MAT 101', 'mat101', 'Mathematics for Everyday Life', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MAT 108', 'mat108', 'Elementary Algebra', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MAT 114', 'mat114', 'Intermediate Algebra', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MAT 120', 'mat120', 'Precalculus', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MAT 201', 'mat201', 'Statistics', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MAT 205', 'mat205', 'Discrete Structures', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MAT 220', 'mat220', 'Calculus I', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MAT 221', 'mat221', 'Calculus II', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MBAE 508', 'mbae508', 'Managerial Economics', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MBAE 509', 'mbae509', 'Resilient Leadership and Organizational Behavior', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MBAE 521', 'mbae521', 'Operations and Project Management', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MBAE 524', 'mbae524', 'Corporate Finance and Accounting', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MBAE 532', 'mbae532', 'Ethical Risk Management and Compliance', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MBAE 570', 'mbae570', 'Information Technology', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MBAE 573', 'mbae573', 'Strategic Brand Marketing', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MBAE 595', 'mbae595', 'Systems and Sustainability', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MBAE 596', 'mbae596', 'Strategy and Entrepreneurial Innovation', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MBAE 699', 'mbae699', 'Business Strategy Capstone', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MET 220', 'met220', 'Statics', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MET 225', 'met225', 'Strength of Materials', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MET 270', 'met270', 'Dynamics', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MET 275', 'met275', 'Introduction to Microprocessors and Microcontrollers', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MET 360', 'met360', 'Manufacturing Processes', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MIL 230', 'mil230', 'United States Military History', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MIL 498', 'mil498', 'Military Studies Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'MUS 210', 'mus210', 'History of Rock and Roll', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BNS 101', 'bns101', 'Introduction to National Security', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BNS 301', 'bns301', 'National Security Ethics and Diversity', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BNS 303', 'bns303', 'Comparative National Security Analysis', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BNS 305', 'bns305', 'Cybersecurity in National Security', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BNS 307', 'bns307', 'Intelligence in National Security', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'BNS 498', 'bns498', 'National Security Capstone', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NS 110', 'ns110', 'Science in Today''s World', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NS 115', 'ns115', 'Introduction to Astronomy', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 210', 'nuc210', 'Health Physics and Radiation Protection', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 211', 'nuc211', 'Radiation Measurement Lab', 1, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 240', 'nuc240', 'Atomic and Nuclear Physics', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 245', 'nuc245', 'Thermodynamics', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 246', 'nuc246', 'Thermal Measurement Laboratory', 1, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 250', 'nuc250', 'Introduction to Heat Transfer and Fluid Mechanics', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 255', 'nuc255', 'Electrical Theory', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 260', 'nuc260', 'Power Plant Components', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 271', 'nuc271', 'Fundamentals of Reactor Safety', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 280', 'nuc280', 'Leading Change in the Nuclear Industry', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 285', 'nuc285', 'Leadership Communications in the Nuclear Industry', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 323', 'nuc323', 'Material Science', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 330', 'nuc330', 'Reactor Core Fundamentals', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 350', 'nuc350', 'Plant Systems Overview', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 360', 'nuc360', 'Nuclear Leadership-Risk Management/Leadership Courage', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUC 495', 'nuc495', 'Integrated Technology Assessment BNX', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 101', 'nur101', 'Introduction to Professional Nursing', 2, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 104', 'nur104', 'Essentials of Nursing Care: Health Safety', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 105', 'nur105', 'Essentials of Nursing Care: Health Differences', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 108', 'nur108', 'Transition to the Professional Nurse Role', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 109', 'nur109', 'Foundations in Nursing Practice', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 209', 'nur209', 'Reproductive Health', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 211', 'nur211', 'Health Differences Across the Life Span 1', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 212', 'nur212', 'Health Differences Across the Life Span 2', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 213', 'nur213', 'Health Differences Across the Life Span 3', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 250', 'nur250', 'Clinical Nursing Practicum: Care of Patients Across the Lifespan', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 275', 'nur275', 'Competencies for Contemporary Nursing Practice', 3, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 290', 'nur290', 'Nursing Capstone: Advanced Clinical Practicum', 4, 1, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 301', 'nur301', 'Bridge for Professional Socialization', 2, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 338', 'nur338', 'Introduction to Informatics for Nurses', 2, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 342', 'nur342', 'Holistic Health Care Across the Lifespan', 4, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 356', 'nur356', 'Leadership and Management in Nursing', 4, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 430', 'nur430', 'Research in Nursing', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 446', 'nur446', 'Teaching and Learning in A Diverse Society', 3, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 448', 'nur448', 'Community Health Nursing: Caring for the Public''s Health', 4, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 462', 'nur462', 'Nursing Capstone', 4, 3, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 502', 'nur502', 'Theoretical Foundations of Nursing Practice', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 503', 'nur503', 'Transformational Nursing:Innovation, Inquiry and Scholarship', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 505', 'nur505', 'Advanced Pathophysiology', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 506', 'nur506', 'Advanced Pharmacology', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 507', 'nur507', 'Advanced Physical Assessment', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 508', 'nur508', 'Research and Evidence-Based Practice', 4, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 515', 'nur515', 'Management Information for Decision Support', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 521', 'nur521', 'Data, Information and Knowledge', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 533', 'nur533', 'Policy, Ethics and Population Health', 4, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 615', 'nur615', 'Management of Clinical Systems', 3, 5, 'https://www.excelsior.edu/catalog/'),
  ('EXCELSIOR', 'NUR 625', 'nur625', 'Management of Fiscal and Operational Systems', 3, 5, 'https://www.excelsior.edu/catalog/')
ON CONFLICT (institution_code, code_norm) DO UPDATE SET title = EXCLUDED.title, credits = EXCLUDED.credits, level_year = EXCLUDED.level_year;