INSERT INTO credit_transfer_rules (source_institution, source_course_code, target_institution, target_course_code, acceptance_status, rule_source, confidence, data_quality, is_active, verified, evidence_url)
VALUES
  ('STUDYCOM', 'Accounting 101', 'EXCELSIOR', 'ACC 211', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Accounting 102', 'EXCELSIOR', 'ACC 212', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Accounting 201', 'EXCELSIOR', 'ACC 314', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Accounting 301', 'EXCELSIOR', 'ACC 360', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Accounting 303', 'EXCELSIOR', 'ACC 360', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Art 103', 'EXCELSIOR', 'ART 101', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Art 104', 'EXCELSIOR', 'ART 102', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Astronomy 101', 'EXCELSIOR', 'NS 115', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Biology 101', 'EXCELSIOR', 'BIO 110', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Biology 102', 'EXCELSIOR', 'BIO 260', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Biology 103', 'EXCELSIOR', 'BIO 212', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 101', 'EXCELSIOR', 'BUS 341', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 102', 'EXCELSIOR', 'BUS 351', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 106', 'EXCELSIOR', 'BUS 312', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 107', 'EXCELSIOR', 'BUS 311', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 120', 'EXCELSIOR', 'BUS 435', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 305', 'EXCELSIOR', 'COMM 423', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 306', 'EXCELSIOR', 'BUS 312', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 307', 'EXCELSIOR', 'BUS 311', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 308', 'EXCELSIOR', 'BUS 435', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 310', 'EXCELSIOR', 'BUS 323', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 311', 'EXCELSIOR', 'IT 390', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 312', 'EXCELSIOR', 'BUS 425', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 313', 'EXCELSIOR', 'COMM 350', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Business 315', 'EXCELSIOR', 'BUS 440', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Chemistry 101', 'EXCELSIOR', 'CHE 101', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Chemistry 111L', 'EXCELSIOR', 'CHE 101', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Chemistry 112L', 'EXCELSIOR', 'CHE 102', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Communications 101', 'EXCELSIOR', 'COMM 125', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Communications 102', 'EXCELSIOR', 'COMM 210', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Communications 120', 'EXCELSIOR', 'COMM 125', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Communications 301', 'EXCELSIOR', 'COMM 320', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Computer Science 306', 'EXCELSIOR', 'ELEC 202', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Computer Science 331', 'EXCELSIOR', 'CYS 450', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Criminal Justice 101', 'EXCELSIOR', 'CJ 101', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Criminal Justice 104', 'EXCELSIOR', 'CJ 324', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Criminal Justice 305', 'EXCELSIOR', 'CJ 301', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Earth Science 101', 'EXCELSIOR', 'GEOL 108', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Economics 101', 'EXCELSIOR', 'ECO 260', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Economics 102', 'EXCELSIOR', 'ECO 262', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'English 204', 'EXCELSIOR', 'ENG 101', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'English 205', 'EXCELSIOR', 'ENG 102', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Finance 101', 'EXCELSIOR', 'BUS 350', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Finance 104', 'EXCELSIOR', 'BUS 350', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Finance 301', 'EXCELSIOR', 'BUS 350', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Finance 303', 'EXCELSIOR', 'BUS 235', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Finance 304', 'EXCELSIOR', 'BUS 437', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Geology 101', 'EXCELSIOR', 'GEOL 108', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Health 103', 'EXCELSIOR', 'HSC 112', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Health 305', 'EXCELSIOR', 'HSC 414', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Health 307', 'EXCELSIOR', 'HSC 432', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Health 309', 'EXCELSIOR', 'HSC 445', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'History 102', 'EXCELSIOR', 'HIS 121', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'History 103', 'EXCELSIOR', 'HIS 101', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'History 104', 'EXCELSIOR', 'HIS 102', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Marketing 301', 'EXCELSIOR', 'BUS 460', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Marketing 302', 'EXCELSIOR', 'BUS 225', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Marketing 303', 'EXCELSIOR', 'BUS 343', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Marketing 308', 'EXCELSIOR', 'BUS 351', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Philosophy 102', 'EXCELSIOR', 'HUM 300', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Philosophy 103', 'EXCELSIOR', 'HUM 300', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Psychology 101', 'EXCELSIOR', 'PSY 101', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Psychology 104', 'EXCELSIOR', 'PSY 360', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Psychology 107', 'EXCELSIOR', 'PSY 235', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Psychology 311', 'EXCELSIOR', 'PSY 380', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Psychology 312', 'EXCELSIOR', 'PSY 440', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Psychology 314', 'EXCELSIOR', 'PSY 340', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Psychology 316', 'EXCELSIOR', 'PSY 360', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html'),
  ('STUDYCOM', 'Sociology 101', 'EXCELSIOR', 'SOC 101', 'accepted', 'study.com_partner_page', 0.95, 'catalog_verified', true, true, 'https://study.com/college/school/excelsior-college.html')
ON CONFLICT (source_institution, source_course_code, target_institution, target_course_code)
DO UPDATE SET
  acceptance_status = EXCLUDED.acceptance_status,
  rule_source = EXCLUDED.rule_source,
  confidence = EXCLUDED.confidence,
  data_quality = EXCLUDED.data_quality,
  is_active = EXCLUDED.is_active,
  verified = EXCLUDED.verified,
  evidence_url = EXCLUDED.evidence_url;

-- Supersede legacy STUDYCOM rules for Excelsior
UPDATE credit_transfer_rules
SET is_active = false
WHERE target_institution = 'EXCELSIOR'
  AND source_institution = 'STUDYCOM'
  AND data_quality = 'legacy_unverified'
  AND is_active = true;