-- Seed COSC transfer rules for SOPHIA and STUDYCOM providers (simple insert)
INSERT INTO credit_transfer_rules (
  source_institution,
  source_course_code,
  target_institution,
  target_course_code,
  acceptance_status,
  confidence,
  rule_source,
  status,
  effective_from
) VALUES
-- SOPHIA Gen Ed courses accepted at COSC
('SOPHIA', 'SOPHIA-ENG-COMP-I-II', 'COSC', 'ENG-101-102', 'accepted', 0.94, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-PUBLIC-SPEAK', 'COSC', 'COM-101', 'accepted', 0.92, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-COLLEGE-ALG', 'COSC', 'MAT-101', 'accepted', 0.93, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-INTRO-ETHICS', 'COSC', 'PHI-101', 'accepted', 0.91, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-ART-HIST', 'COSC', 'ART-101', 'accepted', 0.90, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-INTRO-PSYCH', 'COSC', 'PSY-101', 'accepted', 0.93, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-MICROECON', 'COSC', 'ECO-201', 'accepted', 0.92, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-MACROECON', 'COSC', 'ECO-202', 'accepted', 0.92, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-ENV-SCI', 'COSC', 'SCI-101', 'accepted', 0.90, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-HUMAN-BIO', 'COSC', 'BIO-101', 'accepted', 0.91, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-STATS', 'COSC', 'MAT-201', 'accepted', 0.93, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-MGMT-PRIN', 'COSC', 'MGT-201', 'accepted', 0.92, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-COMM', 'COSC', 'COM-201', 'accepted', 0.91, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-INFO-SYS', 'COSC', 'CIS-201', 'accepted', 0.90, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-PROJECT-MGMT', 'COSC', 'MGT-301', 'accepted', 0.90, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-LEADERSHIP', 'COSC', 'MGT-302', 'accepted', 0.89, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-CRITICAL', 'COSC', 'PHI-201', 'accepted', 0.88, 'ACE', 'active', NOW()),
('SOPHIA', 'SOPHIA-INTRO-SOC', 'COSC', 'SOC-101', 'accepted', 0.91, 'ACE', 'active', NOW()),

-- STUDYCOM Business courses accepted at COSC
('STUDYCOM', 'SDC-FIN-ACCT', 'COSC', 'ACC-201', 'accepted', 0.93, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-MGMT-ACCT', 'COSC', 'ACC-202', 'accepted', 0.92, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-BUS-LAW', 'COSC', 'BUS-201', 'accepted', 0.91, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-MARKETING', 'COSC', 'MKT-201', 'accepted', 0.92, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-FINANCE', 'COSC', 'FIN-201', 'accepted', 0.93, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-HR-MGMT', 'COSC', 'MGT-310', 'accepted', 0.91, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-ORG-BEHAV', 'COSC', 'MGT-320', 'accepted', 0.90, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-OPS-MGMT', 'COSC', 'MGT-330', 'accepted', 0.92, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-STRAT-MGMT', 'COSC', 'MGT-401', 'accepted', 0.93, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-INTL-BUS', 'COSC', 'BUS-301', 'accepted', 0.90, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-BUS-ETHICS', 'COSC', 'BUS-310', 'accepted', 0.89, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-ENTREPRENEURSHIP', 'COSC', 'BUS-320', 'accepted', 0.91, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-SUPPLY-CHAIN', 'COSC', 'MGT-340', 'accepted', 0.90, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-CONSUMER-BEHAV', 'COSC', 'MKT-301', 'accepted', 0.89, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-SALES-MGMT', 'COSC', 'MKT-310', 'accepted', 0.88, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-BUS-ANALYTICS', 'COSC', 'BUS-350', 'accepted', 0.92, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-RISK-MGMT', 'COSC', 'FIN-301', 'accepted', 0.90, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-NEGOTIATIONS', 'COSC', 'BUS-360', 'accepted', 0.88, 'ACE', 'active', NOW()),
('STUDYCOM', 'SDC-CORP-FINANCE', 'COSC', 'FIN-310', 'accepted', 0.92, 'ACE', 'active', NOW());